<?php
require_once 'includes/config.php';
require_once 'includes/functions.php';
require_login();

if ($_SESSION['role'] !== 'admin') {
    header('Location: index.php');
    exit;
}

$id = (int) ($_GET['id'] ?? 0);
if (!$id) {
    header('Location: trial_balance.php');
    exit;
}

$stmt = $pdo->prepare("
    SELECT tb.*, u.username AS generated_by_name
    FROM trial_balances tb
    JOIN users u ON tb.generated_by = u.id
    WHERE tb.id = ?
");
$stmt->execute([$id]);
$tb = $stmt->fetch();

if (!$tb) {
    header('Location: trial_balance.php');
    exit;
}

$lines_stmt = $pdo->prepare("
    SELECT * FROM trial_balance_lines
    WHERE trial_balance_id = ?
    ORDER BY coa_code ASC
");
$lines_stmt->execute([$id]);
$lines = $lines_stmt->fetchAll();

// Group by type
$type_order = ['asset', 'liability', 'equity', 'income', 'expense'];
$grouped = [];
foreach ($lines as $line) {
    $grouped[$line['coa_type']][] = $line;
}

$balanced = (round($tb['total_debits'], 2) === round($tb['total_credits'], 2));

$page_title = 'View Trial Balance';
require_once 'includes/header.php';
require_once 'includes/topbar.php';
require_once 'includes/sidebar.php';
?>

<div class="page-wrapper">
    <div class="page-content">
        <div class="container-fluid">

            <div class="row">
                <div class="col-sm-12">
                    <div class="page-title-box d-md-flex justify-content-md-between align-items-center">
                        <h4 class="page-title"><?php echo htmlspecialchars($tb['label']); ?></h4>
                        <ol class="breadcrumb mb-0">
                            <li class="breadcrumb-item"><a href="index.php">Dashboard</a></li>
                            <li class="breadcrumb-item"><a href="trial_balance.php">Trial Balance</a></li>
                            <li class="breadcrumb-item active">View</li>
                        </ol>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header d-flex justify-content-between align-items-center no-print">
                            <div>
                                <small class="text-muted">
                                    Period: <strong><?php echo date('d M Y', strtotime($tb['date_from'])); ?></strong>
                                    &mdash;
                                    <strong><?php echo date('d M Y', strtotime($tb['date_to'])); ?></strong>
                                    &nbsp;|&nbsp;
                                    Generated by <strong><?php echo htmlspecialchars($tb['generated_by_name']); ?></strong>
                                    on <?php echo date('d M Y H:i', strtotime($tb['generated_at'])); ?>
                                </small>
                            </div>
                            <div>
                                <?php if ($balanced): ?>
                                    <span class="badge bg-success fs-6 me-2">
                                        <i class="fas fa-check-circle me-1"></i> Balanced
                                    </span>
                                <?php else: ?>
                                    <span class="badge bg-danger fs-6 me-2">
                                        <i class="fas fa-exclamation-triangle me-1"></i> Out of Balance
                                    </span>
                                <?php endif; ?>
                                <button onclick="window.print()" class="btn btn-sm btn-outline-secondary me-2">
                                    <i class="fas fa-print me-1"></i> Print
                                </button>
                                <a href="trial_balance.php" class="btn btn-sm btn-outline-primary">
                                    <i class="fas fa-arrow-left me-1"></i> Back
                                </a>
                            </div>
                        </div>

                        <!-- Print header - only shows when printing -->
                        <div class="card-body print-header" style="display:none;">
                            <h3 class="text-center"><?php echo htmlspecialchars($tb['label']); ?></h3>
                            <p class="text-center text-muted">
                                Period: <?php echo date('d M Y', strtotime($tb['date_from'])); ?>
                                &mdash;
                                <?php echo date('d M Y', strtotime($tb['date_to'])); ?>
                            </p>
                        </div>

                        <div class="card-body pt-0">
                            <table class="table table-striped mt-3">
                                <thead class="table-dark">
                                    <tr>
                                        <th>Code</th>
                                        <th>Account Name</th>
                                        <th>Type</th>
                                        <th class="text-end">Debit (£)</th>
                                        <th class="text-end">Credit (£)</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php foreach ($type_order as $type):
                                        if (empty($grouped[$type]))
                                            continue;
                                        ?>
                                    <tr class="table-secondary">
                                        <td colspan="5" class="fw-bold text-uppercase small">
                                            <?php echo ucfirst($type); ?>
                                        </td>
                                    </tr>
                                    <?php foreach ($grouped[$type] as $line):
                                        $has_activity = ($line['debit_amount'] > 0 || $line['credit_amount'] > 0);
                                        ?>
                                    <tr class="<?php echo !$has_activity ? 'text-muted' : ''; ?>">
                                        <td><?php echo htmlspecialchars($line['coa_code']); ?></td>
                                        <td><?php echo htmlspecialchars($line['coa_name']); ?></td>
                                        <td>
                                            <span class="badge
                                                <?php echo match ($line['coa_type']) {
                                                    'asset' => 'bg-primary',
                                                    'liability' => 'bg-warning text-dark',
                                                    'equity' => 'bg-info text-dark',
                                                    'income' => 'bg-success',
                                                    'expense' => 'bg-danger',
                                                    default => 'bg-secondary'
                                                }; ?>">
                                                <?php echo ucfirst($line['coa_type']); ?>
                                            </span>
                                        </td>
                                        <td class="text-end">
                                            <?php echo $line['debit_amount'] > 0
                                                ? number_format($line['debit_amount'], 2)
                                                : '-'; ?>
                                        </td>
                                        <td class="text-end">
                                            <?php echo $line['credit_amount'] > 0
                                                ? number_format($line['credit_amount'], 2)
                                                : '-'; ?>
                                        </td>
                                    </tr>
                                    <?php endforeach; ?>
                                    <?php endforeach; ?>
                                </tbody>
                                <tfoot class="table-dark">
                                    <tr>
                                        <td colspan="3" class="fw-bold text-end">TOTALS</td>
                                        <td class="text-end fw-bold">
                                            £<?php echo number_format($tb['total_debits'], 2); ?>
                                        </td>
                                        <td class="text-end fw-bold">
                                            £<?php echo number_format($tb['total_credits'], 2); ?>
                                        </td>
                                    </tr>
                                </tfoot>
                            </table>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>

<style>
@media print {
    .no-print, nav, .sidebar, .topbar, .btn { display: none !important; }
    .print-header { display: block !important; }
    .page-wrapper { margin: 0 !important; }
    .card { box-shadow: none !important; border: none !important; }
    table { font-size: 12px; }
}
</style>

<?php require_once 'includes/footer.php'; ?>